package com.bbdig.mapper;

import com.bbdig.entity.Googledighistory;
import com.bbdig.entity.GoogledighistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoogledighistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int countByExample(GoogledighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int deleteByExample(GoogledighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int insert(Googledighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int insertSelective(Googledighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	List<Googledighistory> selectByExample(GoogledighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	Googledighistory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Googledighistory record,
			@Param("example") GoogledighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int updateByExample(@Param("record") Googledighistory record, @Param("example") GoogledighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int updateByPrimaryKeySelective(Googledighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table googledighistory
	 * @mbggenerated  Fri May 27 17:51:09 CST 2016
	 */
	int updateByPrimaryKey(Googledighistory record);
}