package com.bbdig.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.HotKeywords1dView;
import com.bbdig.entity.HotKeywords1dViewExample;

public interface HotKeywords1dViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int countByExample(HotKeywords1dViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int deleteByExample(HotKeywords1dViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int insert(HotKeywords1dView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int insertSelective(HotKeywords1dView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    List<HotKeywords1dView> selectByExample(HotKeywords1dViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") HotKeywords1dView record, @Param("example") HotKeywords1dViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords_1d_view
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    int updateByExample(@Param("record") HotKeywords1dView record, @Param("example") HotKeywords1dViewExample example);
    
    List<HotKeywords1dView> selectPage(HotKeywords1dViewExample example,RowBounds bounds); 
}