package com.bbdig.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.HotKeywordsView;
import com.bbdig.entity.HotKeywordsViewExample;

public interface HotKeywordsViewMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int countByExample(HotKeywordsViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int deleteByExample(HotKeywordsViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int insert(HotKeywordsView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int insertSelective(HotKeywordsView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	List<HotKeywordsView> selectByExample(HotKeywordsViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HotKeywordsView record,
			@Param("example") HotKeywordsViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hot_keywords_view
	 * @mbggenerated  Tue Apr 05 14:24:04 CST 2016
	 */
	int updateByExample(@Param("record") HotKeywordsView record, @Param("example") HotKeywordsViewExample example);

	List<HotKeywordsView> selectPage(HotKeywordsViewExample example,RowBounds bounds); 
}