package com.bbdig.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.KeywordsBlock;
import com.bbdig.entity.KeywordsBlockExample;

public interface KeywordsBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int countByExample(KeywordsBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int deleteByExample(KeywordsBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int insert(KeywordsBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int insertSelective(KeywordsBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    List<KeywordsBlock> selectByExample(KeywordsBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    KeywordsBlock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") KeywordsBlock record, @Param("example") KeywordsBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int updateByExample(@Param("record") KeywordsBlock record, @Param("example") KeywordsBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int updateByPrimaryKeySelective(KeywordsBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_block
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    int updateByPrimaryKey(KeywordsBlock record);

	 List<KeywordsBlock> selectPage(KeywordsBlockExample example,RowBounds bounds); 
}