package com.bbdig.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.Keywords;
import com.bbdig.entity.KeywordsExample;

public interface KeywordsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int countByExample(KeywordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int deleteByExample(KeywordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int insert(Keywords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int insertSelective(Keywords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	List<Keywords> selectByExample(KeywordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	Keywords selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Keywords record, @Param("example") KeywordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int updateByExample(@Param("record") Keywords record, @Param("example") KeywordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int updateByPrimaryKeySelective(Keywords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keywords
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	int updateByPrimaryKey(Keywords record);

	List<Keywords> selectPage(KeywordsExample example,RowBounds bounds); 
}