package com.bbdig.mapper;

import com.bbdig.entity.Link;
import com.bbdig.entity.LinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int countByExample(LinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int deleteByExample(LinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int insert(Link record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int insertSelective(Link record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	List<Link> selectByExample(LinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	Link selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int updateByPrimaryKeySelective(Link record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table link
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	int updateByPrimaryKey(Link record);
}