package com.bbdig.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.PostView;
import com.bbdig.entity.PostViewExample;

public interface PostViewMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int countByExample(PostViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int deleteByExample(PostViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int insert(PostView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int insertSelective(PostView record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	List<PostView> selectByExample(PostViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int updateByExampleSelective(@Param("record") PostView record, @Param("example") PostViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	int updateByExample(@Param("record") PostView record, @Param("example") PostViewExample example);

	List<PostView> selectPage(PostViewExample example,RowBounds bounds); 
	 
	 List<PostView> selectPageForFollow(PostViewExample example,RowBounds bounds);  
}