package com.bbdig.mapper;

import org.apache.ibatis.session.RowBounds;

import com.bbdig.entity.Post;
import com.bbdig.entity.PostExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int countByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int deleteByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int insert(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int insertSelective(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	List<Post> selectByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	Post selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int updateByPrimaryKeySelective(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	int updateByPrimaryKey(Post record);

	List<Post> selectPage(PostExample example,RowBounds bounds); 
}