package com.bbdig.mapper;

import com.bbdig.entity.Tiebadighistory;
import com.bbdig.entity.TiebadighistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TiebadighistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int countByExample(TiebadighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int deleteByExample(TiebadighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int insert(Tiebadighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int insertSelective(Tiebadighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	List<Tiebadighistory> selectByExample(TiebadighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	Tiebadighistory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Tiebadighistory record,
			@Param("example") TiebadighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int updateByExample(@Param("record") Tiebadighistory record, @Param("example") TiebadighistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int updateByPrimaryKeySelective(Tiebadighistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	int updateByPrimaryKey(Tiebadighistory record);
}