package com.bbdig.mapper;

import com.bbdig.entity.TrustDomain;
import com.bbdig.entity.TrustDomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrustDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int countByExample(TrustDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int deleteByExample(TrustDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int insert(TrustDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int insertSelective(TrustDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    List<TrustDomain> selectByExample(TrustDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    TrustDomain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") TrustDomain record, @Param("example") TrustDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int updateByExample(@Param("record") TrustDomain record, @Param("example") TrustDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int updateByPrimaryKeySelective(TrustDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trust_domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    int updateByPrimaryKey(TrustDomain record);
}