package com.bbdig.entity;

import java.util.Date;

public class BadWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bad_word.id
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bad_word.word
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bad_word.status
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bad_word.createDate
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bad_word.id
     *
     * @return the value of bad_word.id
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bad_word.id
     *
     * @param id the value for bad_word.id
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bad_word.word
     *
     * @return the value of bad_word.word
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bad_word.word
     *
     * @param word the value for bad_word.word
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bad_word.status
     *
     * @return the value of bad_word.status
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bad_word.status
     *
     * @param status the value for bad_word.status
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bad_word.createDate
     *
     * @return the value of bad_word.createDate
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bad_word.createDate
     *
     * @param createdate the value for bad_word.createDate
     *
     * @mbggenerated Mon Apr 11 16:37:16 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}