package com.bbdig.entity;

import java.util.Date;

public class FollowKeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_keyword.id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_keyword.user_id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_keyword.keyword
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_keyword.createDate
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_keyword.id
     *
     * @return the value of follow_keyword.id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_keyword.id
     *
     * @param id the value for follow_keyword.id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_keyword.user_id
     *
     * @return the value of follow_keyword.user_id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_keyword.user_id
     *
     * @param userId the value for follow_keyword.user_id
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_keyword.keyword
     *
     * @return the value of follow_keyword.keyword
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_keyword.keyword
     *
     * @param keyword the value for follow_keyword.keyword
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_keyword.createDate
     *
     * @return the value of follow_keyword.createDate
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_keyword.createDate
     *
     * @param createdate the value for follow_keyword.createDate
     *
     * @mbggenerated Sat Apr 30 21:18:45 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}