package com.bbdig.entity;

public class HotKeywords1dView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords_1d_view.keyword
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords_1d_view.times
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    private Long times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords_1d_view.useAble
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    private Integer useable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords_1d_view.keyword
     *
     * @return the value of hot_keywords_1d_view.keyword
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords_1d_view.keyword
     *
     * @param keyword the value for hot_keywords_1d_view.keyword
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords_1d_view.times
     *
     * @return the value of hot_keywords_1d_view.times
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public Long getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords_1d_view.times
     *
     * @param times the value for hot_keywords_1d_view.times
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public void setTimes(Long times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords_1d_view.useAble
     *
     * @return the value of hot_keywords_1d_view.useAble
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public Integer getUseable() {
        return useable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords_1d_view.useAble
     *
     * @param useable the value for hot_keywords_1d_view.useAble
     *
     * @mbggenerated Mon Mar 28 20:00:22 CST 2016
     */
    public void setUseable(Integer useable) {
        this.useable = useable;
    }
}