package com.bbdig.entity;

public class KeywordsBlock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywords_block.id
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywords_block.keyword
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywords_block.id
     *
     * @return the value of keywords_block.id
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywords_block.id
     *
     * @param id the value for keywords_block.id
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywords_block.keyword
     *
     * @return the value of keywords_block.keyword
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywords_block.keyword
     *
     * @param keyword the value for keywords_block.keyword
     *
     * @mbggenerated Mon Mar 28 13:32:36 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}