package com.bbdig.entity;

import java.util.Date;

public class Keywords {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keywords.id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keywords.keyword
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keywords.createDate
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keywords.user_id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keywords.id
	 * @return  the value of keywords.id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keywords.id
	 * @param id  the value for keywords.id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keywords.keyword
	 * @return  the value of keywords.keyword
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keywords.keyword
	 * @param keyword  the value for keywords.keyword
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keywords.createDate
	 * @return  the value of keywords.createDate
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keywords.createDate
	 * @param createdate  the value for keywords.createDate
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keywords.user_id
	 * @return  the value of keywords.user_id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keywords.user_id
	 * @param userId  the value for keywords.user_id
	 * @mbggenerated  Sun Mar 27 13:48:57 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}