package com.bbdig.entity;

import java.util.Date;

public class Link {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.id
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.pid
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.title
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.url
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.createDate
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.md5
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private String md5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column link.ts
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	private Integer ts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.id
	 * @return  the value of link.id
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.id
	 * @param id  the value for link.id
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.pid
	 * @return  the value of link.pid
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.pid
	 * @param pid  the value for link.pid
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.title
	 * @return  the value of link.title
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.title
	 * @param title  the value for link.title
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.url
	 * @return  the value of link.url
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.url
	 * @param url  the value for link.url
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.createDate
	 * @return  the value of link.createDate
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.createDate
	 * @param createdate  the value for link.createDate
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.md5
	 * @return  the value of link.md5
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public String getMd5() {
		return md5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.md5
	 * @param md5  the value for link.md5
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setMd5(String md5) {
		this.md5 = md5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column link.ts
	 * @return  the value of link.ts
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public Integer getTs() {
		return ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column link.ts
	 * @param ts  the value for link.ts
	 * @mbggenerated  Tue Jan 10 16:29:21 CST 2017
	 */
	public void setTs(Integer ts) {
		this.ts = ts;
	}
}