package com.bbdig.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public PostViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createDate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createDate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createDate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createDate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createDate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createDate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createDate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createDate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createDate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createDate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createDate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andLinkIsNull() {
			addCriterion("link is null");
			return (Criteria) this;
		}

		public Criteria andLinkIsNotNull() {
			addCriterion("link is not null");
			return (Criteria) this;
		}

		public Criteria andLinkEqualTo(String value) {
			addCriterion("link =", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotEqualTo(String value) {
			addCriterion("link <>", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkGreaterThan(String value) {
			addCriterion("link >", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkGreaterThanOrEqualTo(String value) {
			addCriterion("link >=", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLessThan(String value) {
			addCriterion("link <", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLessThanOrEqualTo(String value) {
			addCriterion("link <=", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkLike(String value) {
			addCriterion("link like", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotLike(String value) {
			addCriterion("link not like", value, "link");
			return (Criteria) this;
		}

		public Criteria andLinkIn(List<String> values) {
			addCriterion("link in", values, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotIn(List<String> values) {
			addCriterion("link not in", values, "link");
			return (Criteria) this;
		}

		public Criteria andLinkBetween(String value1, String value2) {
			addCriterion("link between", value1, value2, "link");
			return (Criteria) this;
		}

		public Criteria andLinkNotBetween(String value1, String value2) {
			addCriterion("link not between", value1, value2, "link");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andDescripIsNull() {
			addCriterion("descrip is null");
			return (Criteria) this;
		}

		public Criteria andDescripIsNotNull() {
			addCriterion("descrip is not null");
			return (Criteria) this;
		}

		public Criteria andDescripEqualTo(String value) {
			addCriterion("descrip =", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotEqualTo(String value) {
			addCriterion("descrip <>", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripGreaterThan(String value) {
			addCriterion("descrip >", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripGreaterThanOrEqualTo(String value) {
			addCriterion("descrip >=", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLessThan(String value) {
			addCriterion("descrip <", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLessThanOrEqualTo(String value) {
			addCriterion("descrip <=", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLike(String value) {
			addCriterion("descrip like", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotLike(String value) {
			addCriterion("descrip not like", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripIn(List<String> values) {
			addCriterion("descrip in", values, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotIn(List<String> values) {
			addCriterion("descrip not in", values, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripBetween(String value1, String value2) {
			addCriterion("descrip between", value1, value2, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotBetween(String value1, String value2) {
			addCriterion("descrip not between", value1, value2, "descrip");
			return (Criteria) this;
		}

		public Criteria andImgurlsIsNull() {
			addCriterion("imgUrls is null");
			return (Criteria) this;
		}

		public Criteria andImgurlsIsNotNull() {
			addCriterion("imgUrls is not null");
			return (Criteria) this;
		}

		public Criteria andImgurlsEqualTo(String value) {
			addCriterion("imgUrls =", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsNotEqualTo(String value) {
			addCriterion("imgUrls <>", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsGreaterThan(String value) {
			addCriterion("imgUrls >", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsGreaterThanOrEqualTo(String value) {
			addCriterion("imgUrls >=", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsLessThan(String value) {
			addCriterion("imgUrls <", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsLessThanOrEqualTo(String value) {
			addCriterion("imgUrls <=", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsLike(String value) {
			addCriterion("imgUrls like", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsNotLike(String value) {
			addCriterion("imgUrls not like", value, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsIn(List<String> values) {
			addCriterion("imgUrls in", values, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsNotIn(List<String> values) {
			addCriterion("imgUrls not in", values, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsBetween(String value1, String value2) {
			addCriterion("imgUrls between", value1, value2, "imgurls");
			return (Criteria) this;
		}

		public Criteria andImgurlsNotBetween(String value1, String value2) {
			addCriterion("imgUrls not between", value1, value2, "imgurls");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andKeywordsIsNull() {
			addCriterion("keywords is null");
			return (Criteria) this;
		}

		public Criteria andKeywordsIsNotNull() {
			addCriterion("keywords is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordsEqualTo(String value) {
			addCriterion("keywords =", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotEqualTo(String value) {
			addCriterion("keywords <>", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsGreaterThan(String value) {
			addCriterion("keywords >", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
			addCriterion("keywords >=", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLessThan(String value) {
			addCriterion("keywords <", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLessThanOrEqualTo(String value) {
			addCriterion("keywords <=", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLike(String value) {
			addCriterion("keywords like", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotLike(String value) {
			addCriterion("keywords not like", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsIn(List<String> values) {
			addCriterion("keywords in", values, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotIn(List<String> values) {
			addCriterion("keywords not in", values, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsBetween(String value1, String value2) {
			addCriterion("keywords between", value1, value2, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotBetween(String value1, String value2) {
			addCriterion("keywords not between", value1, value2, "keywords");
			return (Criteria) this;
		}

		public Criteria andRefPostIdIsNull() {
			addCriterion("ref_post_id is null");
			return (Criteria) this;
		}

		public Criteria andRefPostIdIsNotNull() {
			addCriterion("ref_post_id is not null");
			return (Criteria) this;
		}

		public Criteria andRefPostIdEqualTo(Integer value) {
			addCriterion("ref_post_id =", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdNotEqualTo(Integer value) {
			addCriterion("ref_post_id <>", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdGreaterThan(Integer value) {
			addCriterion("ref_post_id >", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ref_post_id >=", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdLessThan(Integer value) {
			addCriterion("ref_post_id <", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdLessThanOrEqualTo(Integer value) {
			addCriterion("ref_post_id <=", value, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdIn(List<Integer> values) {
			addCriterion("ref_post_id in", values, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdNotIn(List<Integer> values) {
			addCriterion("ref_post_id not in", values, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdBetween(Integer value1, Integer value2) {
			addCriterion("ref_post_id between", value1, value2, "refPostId");
			return (Criteria) this;
		}

		public Criteria andRefPostIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ref_post_id not between", value1, value2, "refPostId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateIsNull() {
			addCriterion("lastUpdateDate is null");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateIsNotNull() {
			addCriterion("lastUpdateDate is not null");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateEqualTo(Date value) {
			addCriterion("lastUpdateDate =", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateNotEqualTo(Date value) {
			addCriterion("lastUpdateDate <>", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateGreaterThan(Date value) {
			addCriterion("lastUpdateDate >", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("lastUpdateDate >=", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateLessThan(Date value) {
			addCriterion("lastUpdateDate <", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateLessThanOrEqualTo(Date value) {
			addCriterion("lastUpdateDate <=", value, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateIn(List<Date> values) {
			addCriterion("lastUpdateDate in", values, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateNotIn(List<Date> values) {
			addCriterion("lastUpdateDate not in", values, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateBetween(Date value1, Date value2) {
			addCriterion("lastUpdateDate between", value1, value2, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andLastupdatedateNotBetween(Date value1, Date value2) {
			addCriterion("lastUpdateDate not between", value1, value2, "lastupdatedate");
			return (Criteria) this;
		}

		public Criteria andZhuicountIsNull() {
			addCriterion("zhuiCount is null");
			return (Criteria) this;
		}

		public Criteria andZhuicountIsNotNull() {
			addCriterion("zhuiCount is not null");
			return (Criteria) this;
		}

		public Criteria andZhuicountEqualTo(Integer value) {
			addCriterion("zhuiCount =", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountNotEqualTo(Integer value) {
			addCriterion("zhuiCount <>", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountGreaterThan(Integer value) {
			addCriterion("zhuiCount >", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountGreaterThanOrEqualTo(Integer value) {
			addCriterion("zhuiCount >=", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountLessThan(Integer value) {
			addCriterion("zhuiCount <", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountLessThanOrEqualTo(Integer value) {
			addCriterion("zhuiCount <=", value, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountIn(List<Integer> values) {
			addCriterion("zhuiCount in", values, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountNotIn(List<Integer> values) {
			addCriterion("zhuiCount not in", values, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountBetween(Integer value1, Integer value2) {
			addCriterion("zhuiCount between", value1, value2, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andZhuicountNotBetween(Integer value1, Integer value2) {
			addCriterion("zhuiCount not between", value1, value2, "zhuicount");
			return (Criteria) this;
		}

		public Criteria andReplycountIsNull() {
			addCriterion("replyCount is null");
			return (Criteria) this;
		}

		public Criteria andReplycountIsNotNull() {
			addCriterion("replyCount is not null");
			return (Criteria) this;
		}

		public Criteria andReplycountEqualTo(Integer value) {
			addCriterion("replyCount =", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountNotEqualTo(Integer value) {
			addCriterion("replyCount <>", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountGreaterThan(Integer value) {
			addCriterion("replyCount >", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountGreaterThanOrEqualTo(Integer value) {
			addCriterion("replyCount >=", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountLessThan(Integer value) {
			addCriterion("replyCount <", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountLessThanOrEqualTo(Integer value) {
			addCriterion("replyCount <=", value, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountIn(List<Integer> values) {
			addCriterion("replyCount in", values, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountNotIn(List<Integer> values) {
			addCriterion("replyCount not in", values, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountBetween(Integer value1, Integer value2) {
			addCriterion("replyCount between", value1, value2, "replycount");
			return (Criteria) this;
		}

		public Criteria andReplycountNotBetween(Integer value1, Integer value2) {
			addCriterion("replyCount not between", value1, value2, "replycount");
			return (Criteria) this;
		}

		public Criteria andUseableIsNull() {
			addCriterion("useAble is null");
			return (Criteria) this;
		}

		public Criteria andUseableIsNotNull() {
			addCriterion("useAble is not null");
			return (Criteria) this;
		}

		public Criteria andUseableEqualTo(Integer value) {
			addCriterion("useAble =", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotEqualTo(Integer value) {
			addCriterion("useAble <>", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableGreaterThan(Integer value) {
			addCriterion("useAble >", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableGreaterThanOrEqualTo(Integer value) {
			addCriterion("useAble >=", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableLessThan(Integer value) {
			addCriterion("useAble <", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableLessThanOrEqualTo(Integer value) {
			addCriterion("useAble <=", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableIn(List<Integer> values) {
			addCriterion("useAble in", values, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotIn(List<Integer> values) {
			addCriterion("useAble not in", values, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableBetween(Integer value1, Integer value2) {
			addCriterion("useAble between", value1, value2, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotBetween(Integer value1, Integer value2) {
			addCriterion("useAble not between", value1, value2, "useable");
			return (Criteria) this;
		}

		public Criteria andBlockflagIsNull() {
			addCriterion("blockFlag is null");
			return (Criteria) this;
		}

		public Criteria andBlockflagIsNotNull() {
			addCriterion("blockFlag is not null");
			return (Criteria) this;
		}

		public Criteria andBlockflagEqualTo(Integer value) {
			addCriterion("blockFlag =", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagNotEqualTo(Integer value) {
			addCriterion("blockFlag <>", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagGreaterThan(Integer value) {
			addCriterion("blockFlag >", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("blockFlag >=", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagLessThan(Integer value) {
			addCriterion("blockFlag <", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagLessThanOrEqualTo(Integer value) {
			addCriterion("blockFlag <=", value, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagIn(List<Integer> values) {
			addCriterion("blockFlag in", values, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagNotIn(List<Integer> values) {
			addCriterion("blockFlag not in", values, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagBetween(Integer value1, Integer value2) {
			addCriterion("blockFlag between", value1, value2, "blockflag");
			return (Criteria) this;
		}

		public Criteria andBlockflagNotBetween(Integer value1, Integer value2) {
			addCriterion("blockFlag not between", value1, value2, "blockflag");
			return (Criteria) this;
		}

		public Criteria andZiyuandouIsNull() {
			addCriterion("ziyuandou is null");
			return (Criteria) this;
		}

		public Criteria andZiyuandouIsNotNull() {
			addCriterion("ziyuandou is not null");
			return (Criteria) this;
		}

		public Criteria andZiyuandouEqualTo(Integer value) {
			addCriterion("ziyuandou =", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouNotEqualTo(Integer value) {
			addCriterion("ziyuandou <>", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouGreaterThan(Integer value) {
			addCriterion("ziyuandou >", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouGreaterThanOrEqualTo(Integer value) {
			addCriterion("ziyuandou >=", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouLessThan(Integer value) {
			addCriterion("ziyuandou <", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouLessThanOrEqualTo(Integer value) {
			addCriterion("ziyuandou <=", value, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouIn(List<Integer> values) {
			addCriterion("ziyuandou in", values, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouNotIn(List<Integer> values) {
			addCriterion("ziyuandou not in", values, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouBetween(Integer value1, Integer value2) {
			addCriterion("ziyuandou between", value1, value2, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andZiyuandouNotBetween(Integer value1, Integer value2) {
			addCriterion("ziyuandou not between", value1, value2, "ziyuandou");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreIsNull() {
			addCriterion("orderByScore is null");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreIsNotNull() {
			addCriterion("orderByScore is not null");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreEqualTo(Integer value) {
			addCriterion("orderByScore =", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreNotEqualTo(Integer value) {
			addCriterion("orderByScore <>", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreGreaterThan(Integer value) {
			addCriterion("orderByScore >", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderByScore >=", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreLessThan(Integer value) {
			addCriterion("orderByScore <", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreLessThanOrEqualTo(Integer value) {
			addCriterion("orderByScore <=", value, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreIn(List<Integer> values) {
			addCriterion("orderByScore in", values, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreNotIn(List<Integer> values) {
			addCriterion("orderByScore not in", values, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreBetween(Integer value1, Integer value2) {
			addCriterion("orderByScore between", value1, value2, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andOrderbyscoreNotBetween(Integer value1, Integer value2) {
			addCriterion("orderByScore not between", value1, value2, "orderbyscore");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesIsNull() {
			addCriterion("traceOpenTimes is null");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesIsNotNull() {
			addCriterion("traceOpenTimes is not null");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesEqualTo(Integer value) {
			addCriterion("traceOpenTimes =", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesNotEqualTo(Integer value) {
			addCriterion("traceOpenTimes <>", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesGreaterThan(Integer value) {
			addCriterion("traceOpenTimes >", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("traceOpenTimes >=", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesLessThan(Integer value) {
			addCriterion("traceOpenTimes <", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesLessThanOrEqualTo(Integer value) {
			addCriterion("traceOpenTimes <=", value, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesIn(List<Integer> values) {
			addCriterion("traceOpenTimes in", values, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesNotIn(List<Integer> values) {
			addCriterion("traceOpenTimes not in", values, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesBetween(Integer value1, Integer value2) {
			addCriterion("traceOpenTimes between", value1, value2, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceopentimesNotBetween(Integer value1, Integer value2) {
			addCriterion("traceOpenTimes not between", value1, value2, "traceopentimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesIsNull() {
			addCriterion("traceUpTimes is null");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesIsNotNull() {
			addCriterion("traceUpTimes is not null");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesEqualTo(Integer value) {
			addCriterion("traceUpTimes =", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesNotEqualTo(Integer value) {
			addCriterion("traceUpTimes <>", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesGreaterThan(Integer value) {
			addCriterion("traceUpTimes >", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("traceUpTimes >=", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesLessThan(Integer value) {
			addCriterion("traceUpTimes <", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesLessThanOrEqualTo(Integer value) {
			addCriterion("traceUpTimes <=", value, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesIn(List<Integer> values) {
			addCriterion("traceUpTimes in", values, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesNotIn(List<Integer> values) {
			addCriterion("traceUpTimes not in", values, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesBetween(Integer value1, Integer value2) {
			addCriterion("traceUpTimes between", value1, value2, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andTraceuptimesNotBetween(Integer value1, Integer value2) {
			addCriterion("traceUpTimes not between", value1, value2, "traceuptimes");
			return (Criteria) this;
		}

		public Criteria andSourcetypeIsNull() {
			addCriterion("sourceType is null");
			return (Criteria) this;
		}

		public Criteria andSourcetypeIsNotNull() {
			addCriterion("sourceType is not null");
			return (Criteria) this;
		}

		public Criteria andSourcetypeEqualTo(Integer value) {
			addCriterion("sourceType =", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeNotEqualTo(Integer value) {
			addCriterion("sourceType <>", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeGreaterThan(Integer value) {
			addCriterion("sourceType >", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sourceType >=", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeLessThan(Integer value) {
			addCriterion("sourceType <", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeLessThanOrEqualTo(Integer value) {
			addCriterion("sourceType <=", value, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeIn(List<Integer> values) {
			addCriterion("sourceType in", values, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeNotIn(List<Integer> values) {
			addCriterion("sourceType not in", values, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeBetween(Integer value1, Integer value2) {
			addCriterion("sourceType between", value1, value2, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andSourcetypeNotBetween(Integer value1, Integer value2) {
			addCriterion("sourceType not between", value1, value2, "sourcetype");
			return (Criteria) this;
		}

		public Criteria andExt1IsNull() {
			addCriterion("ext1 is null");
			return (Criteria) this;
		}

		public Criteria andExt1IsNotNull() {
			addCriterion("ext1 is not null");
			return (Criteria) this;
		}

		public Criteria andExt1EqualTo(String value) {
			addCriterion("ext1 =", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1NotEqualTo(String value) {
			addCriterion("ext1 <>", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1GreaterThan(String value) {
			addCriterion("ext1 >", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1GreaterThanOrEqualTo(String value) {
			addCriterion("ext1 >=", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1LessThan(String value) {
			addCriterion("ext1 <", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1LessThanOrEqualTo(String value) {
			addCriterion("ext1 <=", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1Like(String value) {
			addCriterion("ext1 like", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1NotLike(String value) {
			addCriterion("ext1 not like", value, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1In(List<String> values) {
			addCriterion("ext1 in", values, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1NotIn(List<String> values) {
			addCriterion("ext1 not in", values, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1Between(String value1, String value2) {
			addCriterion("ext1 between", value1, value2, "ext1");
			return (Criteria) this;
		}

		public Criteria andExt1NotBetween(String value1, String value2) {
			addCriterion("ext1 not between", value1, value2, "ext1");
			return (Criteria) this;
		}

		public Criteria andIsrobotIsNull() {
			addCriterion("isRobot is null");
			return (Criteria) this;
		}

		public Criteria andIsrobotIsNotNull() {
			addCriterion("isRobot is not null");
			return (Criteria) this;
		}

		public Criteria andIsrobotEqualTo(Integer value) {
			addCriterion("isRobot =", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotEqualTo(Integer value) {
			addCriterion("isRobot <>", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotGreaterThan(Integer value) {
			addCriterion("isRobot >", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotGreaterThanOrEqualTo(Integer value) {
			addCriterion("isRobot >=", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotLessThan(Integer value) {
			addCriterion("isRobot <", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotLessThanOrEqualTo(Integer value) {
			addCriterion("isRobot <=", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotIn(List<Integer> values) {
			addCriterion("isRobot in", values, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotIn(List<Integer> values) {
			addCriterion("isRobot not in", values, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotBetween(Integer value1, Integer value2) {
			addCriterion("isRobot between", value1, value2, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotBetween(Integer value1, Integer value2) {
			addCriterion("isRobot not between", value1, value2, "isrobot");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickName is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickName is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickName =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickName <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickName >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickName >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickName <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickName <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickName like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickName not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickName in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickName not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickName between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickName not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleIsNull() {
			addCriterion("ref_post_title is null");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleIsNotNull() {
			addCriterion("ref_post_title is not null");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleEqualTo(String value) {
			addCriterion("ref_post_title =", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleNotEqualTo(String value) {
			addCriterion("ref_post_title <>", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleGreaterThan(String value) {
			addCriterion("ref_post_title >", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleGreaterThanOrEqualTo(String value) {
			addCriterion("ref_post_title >=", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleLessThan(String value) {
			addCriterion("ref_post_title <", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleLessThanOrEqualTo(String value) {
			addCriterion("ref_post_title <=", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleLike(String value) {
			addCriterion("ref_post_title like", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleNotLike(String value) {
			addCriterion("ref_post_title not like", value, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleIn(List<String> values) {
			addCriterion("ref_post_title in", values, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleNotIn(List<String> values) {
			addCriterion("ref_post_title not in", values, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleBetween(String value1, String value2) {
			addCriterion("ref_post_title between", value1, value2, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostTitleNotBetween(String value1, String value2) {
			addCriterion("ref_post_title not between", value1, value2, "refPostTitle");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkIsNull() {
			addCriterion("ref_post_link is null");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkIsNotNull() {
			addCriterion("ref_post_link is not null");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkEqualTo(String value) {
			addCriterion("ref_post_link =", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkNotEqualTo(String value) {
			addCriterion("ref_post_link <>", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkGreaterThan(String value) {
			addCriterion("ref_post_link >", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkGreaterThanOrEqualTo(String value) {
			addCriterion("ref_post_link >=", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkLessThan(String value) {
			addCriterion("ref_post_link <", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkLessThanOrEqualTo(String value) {
			addCriterion("ref_post_link <=", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkLike(String value) {
			addCriterion("ref_post_link like", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkNotLike(String value) {
			addCriterion("ref_post_link not like", value, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkIn(List<String> values) {
			addCriterion("ref_post_link in", values, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkNotIn(List<String> values) {
			addCriterion("ref_post_link not in", values, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkBetween(String value1, String value2) {
			addCriterion("ref_post_link between", value1, value2, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andRefPostLinkNotBetween(String value1, String value2) {
			addCriterion("ref_post_link not between", value1, value2, "refPostLink");
			return (Criteria) this;
		}

		public Criteria andDomainNameIsNull() {
			addCriterion("domain_name is null");
			return (Criteria) this;
		}

		public Criteria andDomainNameIsNotNull() {
			addCriterion("domain_name is not null");
			return (Criteria) this;
		}

		public Criteria andDomainNameEqualTo(String value) {
			addCriterion("domain_name =", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameNotEqualTo(String value) {
			addCriterion("domain_name <>", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameGreaterThan(String value) {
			addCriterion("domain_name >", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameGreaterThanOrEqualTo(String value) {
			addCriterion("domain_name >=", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameLessThan(String value) {
			addCriterion("domain_name <", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameLessThanOrEqualTo(String value) {
			addCriterion("domain_name <=", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameLike(String value) {
			addCriterion("domain_name like", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameNotLike(String value) {
			addCriterion("domain_name not like", value, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameIn(List<String> values) {
			addCriterion("domain_name in", values, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameNotIn(List<String> values) {
			addCriterion("domain_name not in", values, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameBetween(String value1, String value2) {
			addCriterion("domain_name between", value1, value2, "domainName");
			return (Criteria) this;
		}

		public Criteria andDomainNameNotBetween(String value1, String value2) {
			addCriterion("domain_name not between", value1, value2, "domainName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post_view
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_view
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 20 14:23:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}