package com.bbdig.entity;

import java.util.Date;

public class PostView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.createDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.descrip
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String descrip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.imgUrls
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String imgurls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.type
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.keywords
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String keywords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.ref_post_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer refPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.user_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.lastUpdateDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Date lastupdatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.zhuiCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer zhuicount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.replyCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer replycount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.useAble
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer useable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.blockFlag
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer blockflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.ziyuandou
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer ziyuandou;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.orderByScore
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer orderbyscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.traceOpenTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer traceopentimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.traceUpTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer traceuptimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.sourceType
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer sourcetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.ext1
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String ext1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.isRobot
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private Integer isrobot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.nickName
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.ref_post_title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String refPostTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.ref_post_link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String refPostLink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post_view.domain_name
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	private String domainName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.id
	 * @return  the value of post_view.id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.id
	 * @param id  the value for post_view.id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.createDate
	 * @return  the value of post_view.createDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.createDate
	 * @param createdate  the value for post_view.createDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.link
	 * @return  the value of post_view.link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.link
	 * @param link  the value for post_view.link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.title
	 * @return  the value of post_view.title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.title
	 * @param title  the value for post_view.title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.descrip
	 * @return  the value of post_view.descrip
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getDescrip() {
		return descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.descrip
	 * @param descrip  the value for post_view.descrip
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.imgUrls
	 * @return  the value of post_view.imgUrls
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getImgurls() {
		return imgurls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.imgUrls
	 * @param imgurls  the value for post_view.imgUrls
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setImgurls(String imgurls) {
		this.imgurls = imgurls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.type
	 * @return  the value of post_view.type
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.type
	 * @param type  the value for post_view.type
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.keywords
	 * @return  the value of post_view.keywords
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.keywords
	 * @param keywords  the value for post_view.keywords
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.ref_post_id
	 * @return  the value of post_view.ref_post_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getRefPostId() {
		return refPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.ref_post_id
	 * @param refPostId  the value for post_view.ref_post_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setRefPostId(Integer refPostId) {
		this.refPostId = refPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.user_id
	 * @return  the value of post_view.user_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.user_id
	 * @param userId  the value for post_view.user_id
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.lastUpdateDate
	 * @return  the value of post_view.lastUpdateDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Date getLastupdatedate() {
		return lastupdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.lastUpdateDate
	 * @param lastupdatedate  the value for post_view.lastUpdateDate
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setLastupdatedate(Date lastupdatedate) {
		this.lastupdatedate = lastupdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.zhuiCount
	 * @return  the value of post_view.zhuiCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getZhuicount() {
		return zhuicount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.zhuiCount
	 * @param zhuicount  the value for post_view.zhuiCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setZhuicount(Integer zhuicount) {
		this.zhuicount = zhuicount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.replyCount
	 * @return  the value of post_view.replyCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getReplycount() {
		return replycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.replyCount
	 * @param replycount  the value for post_view.replyCount
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setReplycount(Integer replycount) {
		this.replycount = replycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.useAble
	 * @return  the value of post_view.useAble
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getUseable() {
		return useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.useAble
	 * @param useable  the value for post_view.useAble
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setUseable(Integer useable) {
		this.useable = useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.blockFlag
	 * @return  the value of post_view.blockFlag
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getBlockflag() {
		return blockflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.blockFlag
	 * @param blockflag  the value for post_view.blockFlag
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setBlockflag(Integer blockflag) {
		this.blockflag = blockflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.ziyuandou
	 * @return  the value of post_view.ziyuandou
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getZiyuandou() {
		return ziyuandou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.ziyuandou
	 * @param ziyuandou  the value for post_view.ziyuandou
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setZiyuandou(Integer ziyuandou) {
		this.ziyuandou = ziyuandou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.orderByScore
	 * @return  the value of post_view.orderByScore
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getOrderbyscore() {
		return orderbyscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.orderByScore
	 * @param orderbyscore  the value for post_view.orderByScore
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setOrderbyscore(Integer orderbyscore) {
		this.orderbyscore = orderbyscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.traceOpenTimes
	 * @return  the value of post_view.traceOpenTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getTraceopentimes() {
		return traceopentimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.traceOpenTimes
	 * @param traceopentimes  the value for post_view.traceOpenTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setTraceopentimes(Integer traceopentimes) {
		this.traceopentimes = traceopentimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.traceUpTimes
	 * @return  the value of post_view.traceUpTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getTraceuptimes() {
		return traceuptimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.traceUpTimes
	 * @param traceuptimes  the value for post_view.traceUpTimes
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setTraceuptimes(Integer traceuptimes) {
		this.traceuptimes = traceuptimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.sourceType
	 * @return  the value of post_view.sourceType
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getSourcetype() {
		return sourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.sourceType
	 * @param sourcetype  the value for post_view.sourceType
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setSourcetype(Integer sourcetype) {
		this.sourcetype = sourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.ext1
	 * @return  the value of post_view.ext1
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getExt1() {
		return ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.ext1
	 * @param ext1  the value for post_view.ext1
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.isRobot
	 * @return  the value of post_view.isRobot
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public Integer getIsrobot() {
		return isrobot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.isRobot
	 * @param isrobot  the value for post_view.isRobot
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setIsrobot(Integer isrobot) {
		this.isrobot = isrobot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.nickName
	 * @return  the value of post_view.nickName
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.nickName
	 * @param nickname  the value for post_view.nickName
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.ref_post_title
	 * @return  the value of post_view.ref_post_title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getRefPostTitle() {
		return refPostTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.ref_post_title
	 * @param refPostTitle  the value for post_view.ref_post_title
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setRefPostTitle(String refPostTitle) {
		this.refPostTitle = refPostTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.ref_post_link
	 * @return  the value of post_view.ref_post_link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getRefPostLink() {
		return refPostLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.ref_post_link
	 * @param refPostLink  the value for post_view.ref_post_link
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setRefPostLink(String refPostLink) {
		this.refPostLink = refPostLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post_view.domain_name
	 * @return  the value of post_view.domain_name
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public String getDomainName() {
		return domainName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post_view.domain_name
	 * @param domainName  the value for post_view.domain_name
	 * @mbggenerated  Thu Jun 16 13:37:17 CST 2016
	 */
	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}
}