package com.bbdig.entity;

import java.util.Date;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.createDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.link
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.title
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.descrip
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String descrip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.imgUrls
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String imgurls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.type
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.keywords
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String keywords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.ref_post_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer refPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.user_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.lastUpdateDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Date lastupdatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.zhuiCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer zhuicount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.replyCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer replycount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.useAble
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer useable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.blockFlag
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer blockflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.ziyuandou
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer ziyuandou;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.sourceType
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer sourcetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.orderByScore
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer orderbyscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.traceOpenTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer traceopentimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.traceUpTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer traceuptimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.ext1
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String ext1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.md5
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private String md5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.domain_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	private Integer domainId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.id
	 * @return  the value of post.id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.id
	 * @param id  the value for post.id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.createDate
	 * @return  the value of post.createDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.createDate
	 * @param createdate  the value for post.createDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.link
	 * @return  the value of post.link
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.link
	 * @param link  the value for post.link
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.title
	 * @return  the value of post.title
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.title
	 * @param title  the value for post.title
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.descrip
	 * @return  the value of post.descrip
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getDescrip() {
		return descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.descrip
	 * @param descrip  the value for post.descrip
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.imgUrls
	 * @return  the value of post.imgUrls
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getImgurls() {
		return imgurls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.imgUrls
	 * @param imgurls  the value for post.imgUrls
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setImgurls(String imgurls) {
		this.imgurls = imgurls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.type
	 * @return  the value of post.type
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.type
	 * @param type  the value for post.type
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.keywords
	 * @return  the value of post.keywords
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.keywords
	 * @param keywords  the value for post.keywords
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.ref_post_id
	 * @return  the value of post.ref_post_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getRefPostId() {
		return refPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.ref_post_id
	 * @param refPostId  the value for post.ref_post_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setRefPostId(Integer refPostId) {
		this.refPostId = refPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.user_id
	 * @return  the value of post.user_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.user_id
	 * @param userId  the value for post.user_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.lastUpdateDate
	 * @return  the value of post.lastUpdateDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Date getLastupdatedate() {
		return lastupdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.lastUpdateDate
	 * @param lastupdatedate  the value for post.lastUpdateDate
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setLastupdatedate(Date lastupdatedate) {
		this.lastupdatedate = lastupdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.zhuiCount
	 * @return  the value of post.zhuiCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getZhuicount() {
		return zhuicount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.zhuiCount
	 * @param zhuicount  the value for post.zhuiCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setZhuicount(Integer zhuicount) {
		this.zhuicount = zhuicount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.replyCount
	 * @return  the value of post.replyCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getReplycount() {
		return replycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.replyCount
	 * @param replycount  the value for post.replyCount
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setReplycount(Integer replycount) {
		this.replycount = replycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.useAble
	 * @return  the value of post.useAble
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getUseable() {
		return useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.useAble
	 * @param useable  the value for post.useAble
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setUseable(Integer useable) {
		this.useable = useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.blockFlag
	 * @return  the value of post.blockFlag
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getBlockflag() {
		return blockflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.blockFlag
	 * @param blockflag  the value for post.blockFlag
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setBlockflag(Integer blockflag) {
		this.blockflag = blockflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.ziyuandou
	 * @return  the value of post.ziyuandou
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getZiyuandou() {
		return ziyuandou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.ziyuandou
	 * @param ziyuandou  the value for post.ziyuandou
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setZiyuandou(Integer ziyuandou) {
		this.ziyuandou = ziyuandou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.sourceType
	 * @return  the value of post.sourceType
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getSourcetype() {
		return sourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.sourceType
	 * @param sourcetype  the value for post.sourceType
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setSourcetype(Integer sourcetype) {
		this.sourcetype = sourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.orderByScore
	 * @return  the value of post.orderByScore
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getOrderbyscore() {
		return orderbyscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.orderByScore
	 * @param orderbyscore  the value for post.orderByScore
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setOrderbyscore(Integer orderbyscore) {
		this.orderbyscore = orderbyscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.traceOpenTimes
	 * @return  the value of post.traceOpenTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getTraceopentimes() {
		return traceopentimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.traceOpenTimes
	 * @param traceopentimes  the value for post.traceOpenTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setTraceopentimes(Integer traceopentimes) {
		this.traceopentimes = traceopentimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.traceUpTimes
	 * @return  the value of post.traceUpTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getTraceuptimes() {
		return traceuptimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.traceUpTimes
	 * @param traceuptimes  the value for post.traceUpTimes
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setTraceuptimes(Integer traceuptimes) {
		this.traceuptimes = traceuptimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.ext1
	 * @return  the value of post.ext1
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getExt1() {
		return ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.ext1
	 * @param ext1  the value for post.ext1
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.md5
	 * @return  the value of post.md5
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public String getMd5() {
		return md5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.md5
	 * @param md5  the value for post.md5
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setMd5(String md5) {
		this.md5 = md5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.domain_id
	 * @return  the value of post.domain_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public Integer getDomainId() {
		return domainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.domain_id
	 * @param domainId  the value for post.domain_id
	 * @mbggenerated  Wed Jun 15 22:12:50 CST 2016
	 */
	public void setDomainId(Integer domainId) {
		this.domainId = domainId;
	}
}