package com.bbdig.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class TiebadighistoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public TiebadighistoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTieziidIsNull() {
			addCriterion("tieziID is null");
			return (Criteria) this;
		}

		public Criteria andTieziidIsNotNull() {
			addCriterion("tieziID is not null");
			return (Criteria) this;
		}

		public Criteria andTieziidEqualTo(String value) {
			addCriterion("tieziID =", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidNotEqualTo(String value) {
			addCriterion("tieziID <>", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidGreaterThan(String value) {
			addCriterion("tieziID >", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidGreaterThanOrEqualTo(String value) {
			addCriterion("tieziID >=", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidLessThan(String value) {
			addCriterion("tieziID <", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidLessThanOrEqualTo(String value) {
			addCriterion("tieziID <=", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidLike(String value) {
			addCriterion("tieziID like", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidNotLike(String value) {
			addCriterion("tieziID not like", value, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidIn(List<String> values) {
			addCriterion("tieziID in", values, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidNotIn(List<String> values) {
			addCriterion("tieziID not in", values, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidBetween(String value1, String value2) {
			addCriterion("tieziID between", value1, value2, "tieziid");
			return (Criteria) this;
		}

		public Criteria andTieziidNotBetween(String value1, String value2) {
			addCriterion("tieziID not between", value1, value2, "tieziid");
			return (Criteria) this;
		}

		public Criteria andPagenumIsNull() {
			addCriterion("pageNum is null");
			return (Criteria) this;
		}

		public Criteria andPagenumIsNotNull() {
			addCriterion("pageNum is not null");
			return (Criteria) this;
		}

		public Criteria andPagenumEqualTo(Integer value) {
			addCriterion("pageNum =", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumNotEqualTo(Integer value) {
			addCriterion("pageNum <>", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumGreaterThan(Integer value) {
			addCriterion("pageNum >", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumGreaterThanOrEqualTo(Integer value) {
			addCriterion("pageNum >=", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumLessThan(Integer value) {
			addCriterion("pageNum <", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumLessThanOrEqualTo(Integer value) {
			addCriterion("pageNum <=", value, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumIn(List<Integer> values) {
			addCriterion("pageNum in", values, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumNotIn(List<Integer> values) {
			addCriterion("pageNum not in", values, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumBetween(Integer value1, Integer value2) {
			addCriterion("pageNum between", value1, value2, "pagenum");
			return (Criteria) this;
		}

		public Criteria andPagenumNotBetween(Integer value1, Integer value2) {
			addCriterion("pageNum not between", value1, value2, "pagenum");
			return (Criteria) this;
		}

		public Criteria andFoundtimesIsNull() {
			addCriterion("foundTimes is null");
			return (Criteria) this;
		}

		public Criteria andFoundtimesIsNotNull() {
			addCriterion("foundTimes is not null");
			return (Criteria) this;
		}

		public Criteria andFoundtimesEqualTo(Integer value) {
			addCriterion("foundTimes =", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesNotEqualTo(Integer value) {
			addCriterion("foundTimes <>", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesGreaterThan(Integer value) {
			addCriterion("foundTimes >", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("foundTimes >=", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesLessThan(Integer value) {
			addCriterion("foundTimes <", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesLessThanOrEqualTo(Integer value) {
			addCriterion("foundTimes <=", value, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesIn(List<Integer> values) {
			addCriterion("foundTimes in", values, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesNotIn(List<Integer> values) {
			addCriterion("foundTimes not in", values, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesBetween(Integer value1, Integer value2) {
			addCriterion("foundTimes between", value1, value2, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andFoundtimesNotBetween(Integer value1, Integer value2) {
			addCriterion("foundTimes not between", value1, value2, "foundtimes");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeIsNull() {
			addCriterion("lastDigTime is null");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeIsNotNull() {
			addCriterion("lastDigTime is not null");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeEqualTo(Date value) {
			addCriterion("lastDigTime =", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeNotEqualTo(Date value) {
			addCriterion("lastDigTime <>", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeGreaterThan(Date value) {
			addCriterion("lastDigTime >", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lastDigTime >=", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeLessThan(Date value) {
			addCriterion("lastDigTime <", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeLessThanOrEqualTo(Date value) {
			addCriterion("lastDigTime <=", value, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeIn(List<Date> values) {
			addCriterion("lastDigTime in", values, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeNotIn(List<Date> values) {
			addCriterion("lastDigTime not in", values, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeBetween(Date value1, Date value2) {
			addCriterion("lastDigTime between", value1, value2, "lastdigtime");
			return (Criteria) this;
		}

		public Criteria andLastdigtimeNotBetween(Date value1, Date value2) {
			addCriterion("lastDigTime not between", value1, value2, "lastdigtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tiebadighistory
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tiebadighistory
     *
     * @mbggenerated do_not_delete_during_merge Fri May 27 11:17:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}