package com.bbdig.entity;

import java.util.Date;

public class Tiebadighistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiebadighistory.id
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiebadighistory.tieziID
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	private String tieziid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiebadighistory.pageNum
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	private Integer pagenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiebadighistory.foundTimes
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	private Integer foundtimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiebadighistory.lastDigTime
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	private Date lastdigtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiebadighistory.id
	 * @return  the value of tiebadighistory.id
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiebadighistory.id
	 * @param id  the value for tiebadighistory.id
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiebadighistory.tieziID
	 * @return  the value of tiebadighistory.tieziID
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public String getTieziid() {
		return tieziid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiebadighistory.tieziID
	 * @param tieziid  the value for tiebadighistory.tieziID
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setTieziid(String tieziid) {
		this.tieziid = tieziid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiebadighistory.pageNum
	 * @return  the value of tiebadighistory.pageNum
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Integer getPagenum() {
		return pagenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiebadighistory.pageNum
	 * @param pagenum  the value for tiebadighistory.pageNum
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setPagenum(Integer pagenum) {
		this.pagenum = pagenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiebadighistory.foundTimes
	 * @return  the value of tiebadighistory.foundTimes
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Integer getFoundtimes() {
		return foundtimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiebadighistory.foundTimes
	 * @param foundtimes  the value for tiebadighistory.foundTimes
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setFoundtimes(Integer foundtimes) {
		this.foundtimes = foundtimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiebadighistory.lastDigTime
	 * @return  the value of tiebadighistory.lastDigTime
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public Date getLastdigtime() {
		return lastdigtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiebadighistory.lastDigTime
	 * @param lastdigtime  the value for tiebadighistory.lastDigTime
	 * @mbggenerated  Fri May 27 11:37:55 CST 2016
	 */
	public void setLastdigtime(Date lastdigtime) {
		this.lastdigtime = lastdigtime;
	}
}