package com.bbdig.entity;

import java.util.Date;

public class TrustDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trust_domain.id
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trust_domain.name
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trust_domain.domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trust_domain.useable
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    private Integer useable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trust_domain.createDate
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trust_domain.id
     *
     * @return the value of trust_domain.id
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trust_domain.id
     *
     * @param id the value for trust_domain.id
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trust_domain.name
     *
     * @return the value of trust_domain.name
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trust_domain.name
     *
     * @param name the value for trust_domain.name
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trust_domain.domain
     *
     * @return the value of trust_domain.domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trust_domain.domain
     *
     * @param domain the value for trust_domain.domain
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trust_domain.useable
     *
     * @return the value of trust_domain.useable
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public Integer getUseable() {
        return useable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trust_domain.useable
     *
     * @param useable the value for trust_domain.useable
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public void setUseable(Integer useable) {
        this.useable = useable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trust_domain.createDate
     *
     * @return the value of trust_domain.createDate
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trust_domain.createDate
     *
     * @param createdate the value for trust_domain.createDate
     *
     * @mbggenerated Thu Jun 16 13:37:43 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}