package com.bbdig.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.headImgUrl
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String headimgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qq
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.loginName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.useAble
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer useable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.followCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer followcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fansCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer fanscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.postCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer postcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.descrip
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String descrip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.createDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.xingzuo
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer xingzuo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.xuexing
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String xuexing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.guxiang
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String guxiang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.suozaidi
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String suozaidi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.school
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isRobot
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer isrobot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastLoginDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Date lastlogindate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.openID
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.loginTimes
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer logintimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.score
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.scoreCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer scorecount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mute
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer mute;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isAdmin
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	private Integer isadmin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickName
	 * @return  the value of user.nickName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickName
	 * @param nickname  the value for user.nickName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.headImgUrl
	 * @return  the value of user.headImgUrl
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getHeadimgurl() {
		return headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.headImgUrl
	 * @param headimgurl  the value for user.headImgUrl
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qq
	 * @return  the value of user.qq
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qq
	 * @param qq  the value for user.qq
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.loginName
	 * @return  the value of user.loginName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.loginName
	 * @param loginname  the value for user.loginName
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.useAble
	 * @return  the value of user.useAble
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getUseable() {
		return useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.useAble
	 * @param useable  the value for user.useAble
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setUseable(Integer useable) {
		this.useable = useable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.followCount
	 * @return  the value of user.followCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getFollowcount() {
		return followcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.followCount
	 * @param followcount  the value for user.followCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setFollowcount(Integer followcount) {
		this.followcount = followcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fansCount
	 * @return  the value of user.fansCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getFanscount() {
		return fanscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fansCount
	 * @param fanscount  the value for user.fansCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setFanscount(Integer fanscount) {
		this.fanscount = fanscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.postCount
	 * @return  the value of user.postCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getPostcount() {
		return postcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.postCount
	 * @param postcount  the value for user.postCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setPostcount(Integer postcount) {
		this.postcount = postcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.descrip
	 * @return  the value of user.descrip
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getDescrip() {
		return descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.descrip
	 * @param descrip  the value for user.descrip
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createDate
	 * @return  the value of user.createDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createDate
	 * @param createdate  the value for user.createDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.xingzuo
	 * @return  the value of user.xingzuo
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getXingzuo() {
		return xingzuo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.xingzuo
	 * @param xingzuo  the value for user.xingzuo
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setXingzuo(Integer xingzuo) {
		this.xingzuo = xingzuo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.xuexing
	 * @return  the value of user.xuexing
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getXuexing() {
		return xuexing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.xuexing
	 * @param xuexing  the value for user.xuexing
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setXuexing(String xuexing) {
		this.xuexing = xuexing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.guxiang
	 * @return  the value of user.guxiang
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getGuxiang() {
		return guxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.guxiang
	 * @param guxiang  the value for user.guxiang
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setGuxiang(String guxiang) {
		this.guxiang = guxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.suozaidi
	 * @return  the value of user.suozaidi
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getSuozaidi() {
		return suozaidi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.suozaidi
	 * @param suozaidi  the value for user.suozaidi
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setSuozaidi(String suozaidi) {
		this.suozaidi = suozaidi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.school
	 * @return  the value of user.school
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.school
	 * @param school  the value for user.school
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isRobot
	 * @return  the value of user.isRobot
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getIsrobot() {
		return isrobot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isRobot
	 * @param isrobot  the value for user.isRobot
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setIsrobot(Integer isrobot) {
		this.isrobot = isrobot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastLoginDate
	 * @return  the value of user.lastLoginDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Date getLastlogindate() {
		return lastlogindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastLoginDate
	 * @param lastlogindate  the value for user.lastLoginDate
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.openID
	 * @return  the value of user.openID
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.openID
	 * @param openid  the value for user.openID
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.loginTimes
	 * @return  the value of user.loginTimes
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getLogintimes() {
		return logintimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.loginTimes
	 * @param logintimes  the value for user.loginTimes
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setLogintimes(Integer logintimes) {
		this.logintimes = logintimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.score
	 * @return  the value of user.score
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.score
	 * @param score  the value for user.score
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.scoreCount
	 * @return  the value of user.scoreCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getScorecount() {
		return scorecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.scoreCount
	 * @param scorecount  the value for user.scoreCount
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setScorecount(Integer scorecount) {
		this.scorecount = scorecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mute
	 * @return  the value of user.mute
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getMute() {
		return mute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mute
	 * @param mute  the value for user.mute
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setMute(Integer mute) {
		this.mute = mute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isAdmin
	 * @return  the value of user.isAdmin
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Integer getIsadmin() {
		return isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isAdmin
	 * @param isadmin  the value for user.isAdmin
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setIsadmin(Integer isadmin) {
		this.isadmin = isadmin;
	}
}