package com.bbdig.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickName is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickName is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickName =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickName <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickName >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickName >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickName <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickName <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickName like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickName not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickName in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickName not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickName between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickName not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlIsNull() {
			addCriterion("headImgUrl is null");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlIsNotNull() {
			addCriterion("headImgUrl is not null");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlEqualTo(String value) {
			addCriterion("headImgUrl =", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlNotEqualTo(String value) {
			addCriterion("headImgUrl <>", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlGreaterThan(String value) {
			addCriterion("headImgUrl >", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlGreaterThanOrEqualTo(String value) {
			addCriterion("headImgUrl >=", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlLessThan(String value) {
			addCriterion("headImgUrl <", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlLessThanOrEqualTo(String value) {
			addCriterion("headImgUrl <=", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlLike(String value) {
			addCriterion("headImgUrl like", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlNotLike(String value) {
			addCriterion("headImgUrl not like", value, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlIn(List<String> values) {
			addCriterion("headImgUrl in", values, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlNotIn(List<String> values) {
			addCriterion("headImgUrl not in", values, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlBetween(String value1, String value2) {
			addCriterion("headImgUrl between", value1, value2, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andHeadimgurlNotBetween(String value1, String value2) {
			addCriterion("headImgUrl not between", value1, value2, "headimgurl");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("qq is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("qq is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("qq =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("qq <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("qq >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("qq >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("qq <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("qq <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("qq like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("qq not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("qq in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("qq not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("qq between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("qq not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andLoginnameIsNull() {
			addCriterion("loginName is null");
			return (Criteria) this;
		}

		public Criteria andLoginnameIsNotNull() {
			addCriterion("loginName is not null");
			return (Criteria) this;
		}

		public Criteria andLoginnameEqualTo(String value) {
			addCriterion("loginName =", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotEqualTo(String value) {
			addCriterion("loginName <>", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameGreaterThan(String value) {
			addCriterion("loginName >", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameGreaterThanOrEqualTo(String value) {
			addCriterion("loginName >=", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLessThan(String value) {
			addCriterion("loginName <", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLessThanOrEqualTo(String value) {
			addCriterion("loginName <=", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLike(String value) {
			addCriterion("loginName like", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotLike(String value) {
			addCriterion("loginName not like", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameIn(List<String> values) {
			addCriterion("loginName in", values, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotIn(List<String> values) {
			addCriterion("loginName not in", values, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameBetween(String value1, String value2) {
			addCriterion("loginName between", value1, value2, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotBetween(String value1, String value2) {
			addCriterion("loginName not between", value1, value2, "loginname");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andUseableIsNull() {
			addCriterion("useAble is null");
			return (Criteria) this;
		}

		public Criteria andUseableIsNotNull() {
			addCriterion("useAble is not null");
			return (Criteria) this;
		}

		public Criteria andUseableEqualTo(Integer value) {
			addCriterion("useAble =", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotEqualTo(Integer value) {
			addCriterion("useAble <>", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableGreaterThan(Integer value) {
			addCriterion("useAble >", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableGreaterThanOrEqualTo(Integer value) {
			addCriterion("useAble >=", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableLessThan(Integer value) {
			addCriterion("useAble <", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableLessThanOrEqualTo(Integer value) {
			addCriterion("useAble <=", value, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableIn(List<Integer> values) {
			addCriterion("useAble in", values, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotIn(List<Integer> values) {
			addCriterion("useAble not in", values, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableBetween(Integer value1, Integer value2) {
			addCriterion("useAble between", value1, value2, "useable");
			return (Criteria) this;
		}

		public Criteria andUseableNotBetween(Integer value1, Integer value2) {
			addCriterion("useAble not between", value1, value2, "useable");
			return (Criteria) this;
		}

		public Criteria andFollowcountIsNull() {
			addCriterion("followCount is null");
			return (Criteria) this;
		}

		public Criteria andFollowcountIsNotNull() {
			addCriterion("followCount is not null");
			return (Criteria) this;
		}

		public Criteria andFollowcountEqualTo(Integer value) {
			addCriterion("followCount =", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotEqualTo(Integer value) {
			addCriterion("followCount <>", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountGreaterThan(Integer value) {
			addCriterion("followCount >", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("followCount >=", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountLessThan(Integer value) {
			addCriterion("followCount <", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountLessThanOrEqualTo(Integer value) {
			addCriterion("followCount <=", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountIn(List<Integer> values) {
			addCriterion("followCount in", values, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotIn(List<Integer> values) {
			addCriterion("followCount not in", values, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountBetween(Integer value1, Integer value2) {
			addCriterion("followCount between", value1, value2, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotBetween(Integer value1, Integer value2) {
			addCriterion("followCount not between", value1, value2, "followcount");
			return (Criteria) this;
		}

		public Criteria andFanscountIsNull() {
			addCriterion("fansCount is null");
			return (Criteria) this;
		}

		public Criteria andFanscountIsNotNull() {
			addCriterion("fansCount is not null");
			return (Criteria) this;
		}

		public Criteria andFanscountEqualTo(Integer value) {
			addCriterion("fansCount =", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountNotEqualTo(Integer value) {
			addCriterion("fansCount <>", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountGreaterThan(Integer value) {
			addCriterion("fansCount >", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountGreaterThanOrEqualTo(Integer value) {
			addCriterion("fansCount >=", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountLessThan(Integer value) {
			addCriterion("fansCount <", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountLessThanOrEqualTo(Integer value) {
			addCriterion("fansCount <=", value, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountIn(List<Integer> values) {
			addCriterion("fansCount in", values, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountNotIn(List<Integer> values) {
			addCriterion("fansCount not in", values, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountBetween(Integer value1, Integer value2) {
			addCriterion("fansCount between", value1, value2, "fanscount");
			return (Criteria) this;
		}

		public Criteria andFanscountNotBetween(Integer value1, Integer value2) {
			addCriterion("fansCount not between", value1, value2, "fanscount");
			return (Criteria) this;
		}

		public Criteria andPostcountIsNull() {
			addCriterion("postCount is null");
			return (Criteria) this;
		}

		public Criteria andPostcountIsNotNull() {
			addCriterion("postCount is not null");
			return (Criteria) this;
		}

		public Criteria andPostcountEqualTo(Integer value) {
			addCriterion("postCount =", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountNotEqualTo(Integer value) {
			addCriterion("postCount <>", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountGreaterThan(Integer value) {
			addCriterion("postCount >", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("postCount >=", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountLessThan(Integer value) {
			addCriterion("postCount <", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountLessThanOrEqualTo(Integer value) {
			addCriterion("postCount <=", value, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountIn(List<Integer> values) {
			addCriterion("postCount in", values, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountNotIn(List<Integer> values) {
			addCriterion("postCount not in", values, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountBetween(Integer value1, Integer value2) {
			addCriterion("postCount between", value1, value2, "postcount");
			return (Criteria) this;
		}

		public Criteria andPostcountNotBetween(Integer value1, Integer value2) {
			addCriterion("postCount not between", value1, value2, "postcount");
			return (Criteria) this;
		}

		public Criteria andDescripIsNull() {
			addCriterion("descrip is null");
			return (Criteria) this;
		}

		public Criteria andDescripIsNotNull() {
			addCriterion("descrip is not null");
			return (Criteria) this;
		}

		public Criteria andDescripEqualTo(String value) {
			addCriterion("descrip =", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotEqualTo(String value) {
			addCriterion("descrip <>", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripGreaterThan(String value) {
			addCriterion("descrip >", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripGreaterThanOrEqualTo(String value) {
			addCriterion("descrip >=", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLessThan(String value) {
			addCriterion("descrip <", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLessThanOrEqualTo(String value) {
			addCriterion("descrip <=", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripLike(String value) {
			addCriterion("descrip like", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotLike(String value) {
			addCriterion("descrip not like", value, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripIn(List<String> values) {
			addCriterion("descrip in", values, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotIn(List<String> values) {
			addCriterion("descrip not in", values, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripBetween(String value1, String value2) {
			addCriterion("descrip between", value1, value2, "descrip");
			return (Criteria) this;
		}

		public Criteria andDescripNotBetween(String value1, String value2) {
			addCriterion("descrip not between", value1, value2, "descrip");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createDate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createDate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createDate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createDate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createDate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createDate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createDate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createDate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createDate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createDate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createDate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andXingzuoIsNull() {
			addCriterion("xingzuo is null");
			return (Criteria) this;
		}

		public Criteria andXingzuoIsNotNull() {
			addCriterion("xingzuo is not null");
			return (Criteria) this;
		}

		public Criteria andXingzuoEqualTo(Integer value) {
			addCriterion("xingzuo =", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoNotEqualTo(Integer value) {
			addCriterion("xingzuo <>", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoGreaterThan(Integer value) {
			addCriterion("xingzuo >", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoGreaterThanOrEqualTo(Integer value) {
			addCriterion("xingzuo >=", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoLessThan(Integer value) {
			addCriterion("xingzuo <", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoLessThanOrEqualTo(Integer value) {
			addCriterion("xingzuo <=", value, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoIn(List<Integer> values) {
			addCriterion("xingzuo in", values, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoNotIn(List<Integer> values) {
			addCriterion("xingzuo not in", values, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoBetween(Integer value1, Integer value2) {
			addCriterion("xingzuo between", value1, value2, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXingzuoNotBetween(Integer value1, Integer value2) {
			addCriterion("xingzuo not between", value1, value2, "xingzuo");
			return (Criteria) this;
		}

		public Criteria andXuexingIsNull() {
			addCriterion("xuexing is null");
			return (Criteria) this;
		}

		public Criteria andXuexingIsNotNull() {
			addCriterion("xuexing is not null");
			return (Criteria) this;
		}

		public Criteria andXuexingEqualTo(String value) {
			addCriterion("xuexing =", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingNotEqualTo(String value) {
			addCriterion("xuexing <>", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingGreaterThan(String value) {
			addCriterion("xuexing >", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingGreaterThanOrEqualTo(String value) {
			addCriterion("xuexing >=", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingLessThan(String value) {
			addCriterion("xuexing <", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingLessThanOrEqualTo(String value) {
			addCriterion("xuexing <=", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingLike(String value) {
			addCriterion("xuexing like", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingNotLike(String value) {
			addCriterion("xuexing not like", value, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingIn(List<String> values) {
			addCriterion("xuexing in", values, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingNotIn(List<String> values) {
			addCriterion("xuexing not in", values, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingBetween(String value1, String value2) {
			addCriterion("xuexing between", value1, value2, "xuexing");
			return (Criteria) this;
		}

		public Criteria andXuexingNotBetween(String value1, String value2) {
			addCriterion("xuexing not between", value1, value2, "xuexing");
			return (Criteria) this;
		}

		public Criteria andGuxiangIsNull() {
			addCriterion("guxiang is null");
			return (Criteria) this;
		}

		public Criteria andGuxiangIsNotNull() {
			addCriterion("guxiang is not null");
			return (Criteria) this;
		}

		public Criteria andGuxiangEqualTo(String value) {
			addCriterion("guxiang =", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangNotEqualTo(String value) {
			addCriterion("guxiang <>", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangGreaterThan(String value) {
			addCriterion("guxiang >", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangGreaterThanOrEqualTo(String value) {
			addCriterion("guxiang >=", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangLessThan(String value) {
			addCriterion("guxiang <", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangLessThanOrEqualTo(String value) {
			addCriterion("guxiang <=", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangLike(String value) {
			addCriterion("guxiang like", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangNotLike(String value) {
			addCriterion("guxiang not like", value, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangIn(List<String> values) {
			addCriterion("guxiang in", values, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangNotIn(List<String> values) {
			addCriterion("guxiang not in", values, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangBetween(String value1, String value2) {
			addCriterion("guxiang between", value1, value2, "guxiang");
			return (Criteria) this;
		}

		public Criteria andGuxiangNotBetween(String value1, String value2) {
			addCriterion("guxiang not between", value1, value2, "guxiang");
			return (Criteria) this;
		}

		public Criteria andSuozaidiIsNull() {
			addCriterion("suozaidi is null");
			return (Criteria) this;
		}

		public Criteria andSuozaidiIsNotNull() {
			addCriterion("suozaidi is not null");
			return (Criteria) this;
		}

		public Criteria andSuozaidiEqualTo(String value) {
			addCriterion("suozaidi =", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiNotEqualTo(String value) {
			addCriterion("suozaidi <>", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiGreaterThan(String value) {
			addCriterion("suozaidi >", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiGreaterThanOrEqualTo(String value) {
			addCriterion("suozaidi >=", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiLessThan(String value) {
			addCriterion("suozaidi <", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiLessThanOrEqualTo(String value) {
			addCriterion("suozaidi <=", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiLike(String value) {
			addCriterion("suozaidi like", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiNotLike(String value) {
			addCriterion("suozaidi not like", value, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiIn(List<String> values) {
			addCriterion("suozaidi in", values, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiNotIn(List<String> values) {
			addCriterion("suozaidi not in", values, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiBetween(String value1, String value2) {
			addCriterion("suozaidi between", value1, value2, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSuozaidiNotBetween(String value1, String value2) {
			addCriterion("suozaidi not between", value1, value2, "suozaidi");
			return (Criteria) this;
		}

		public Criteria andSchoolIsNull() {
			addCriterion("school is null");
			return (Criteria) this;
		}

		public Criteria andSchoolIsNotNull() {
			addCriterion("school is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolEqualTo(String value) {
			addCriterion("school =", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotEqualTo(String value) {
			addCriterion("school <>", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolGreaterThan(String value) {
			addCriterion("school >", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolGreaterThanOrEqualTo(String value) {
			addCriterion("school >=", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLessThan(String value) {
			addCriterion("school <", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLessThanOrEqualTo(String value) {
			addCriterion("school <=", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLike(String value) {
			addCriterion("school like", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotLike(String value) {
			addCriterion("school not like", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolIn(List<String> values) {
			addCriterion("school in", values, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotIn(List<String> values) {
			addCriterion("school not in", values, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolBetween(String value1, String value2) {
			addCriterion("school between", value1, value2, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotBetween(String value1, String value2) {
			addCriterion("school not between", value1, value2, "school");
			return (Criteria) this;
		}

		public Criteria andIsrobotIsNull() {
			addCriterion("isRobot is null");
			return (Criteria) this;
		}

		public Criteria andIsrobotIsNotNull() {
			addCriterion("isRobot is not null");
			return (Criteria) this;
		}

		public Criteria andIsrobotEqualTo(Integer value) {
			addCriterion("isRobot =", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotEqualTo(Integer value) {
			addCriterion("isRobot <>", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotGreaterThan(Integer value) {
			addCriterion("isRobot >", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotGreaterThanOrEqualTo(Integer value) {
			addCriterion("isRobot >=", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotLessThan(Integer value) {
			addCriterion("isRobot <", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotLessThanOrEqualTo(Integer value) {
			addCriterion("isRobot <=", value, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotIn(List<Integer> values) {
			addCriterion("isRobot in", values, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotIn(List<Integer> values) {
			addCriterion("isRobot not in", values, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotBetween(Integer value1, Integer value2) {
			addCriterion("isRobot between", value1, value2, "isrobot");
			return (Criteria) this;
		}

		public Criteria andIsrobotNotBetween(Integer value1, Integer value2) {
			addCriterion("isRobot not between", value1, value2, "isrobot");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIsNull() {
			addCriterion("lastLoginDate is null");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIsNotNull() {
			addCriterion("lastLoginDate is not null");
			return (Criteria) this;
		}

		public Criteria andLastlogindateEqualTo(Date value) {
			addCriterion("lastLoginDate =", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotEqualTo(Date value) {
			addCriterion("lastLoginDate <>", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateGreaterThan(Date value) {
			addCriterion("lastLoginDate >", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateGreaterThanOrEqualTo(Date value) {
			addCriterion("lastLoginDate >=", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateLessThan(Date value) {
			addCriterion("lastLoginDate <", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateLessThanOrEqualTo(Date value) {
			addCriterion("lastLoginDate <=", value, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateIn(List<Date> values) {
			addCriterion("lastLoginDate in", values, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotIn(List<Date> values) {
			addCriterion("lastLoginDate not in", values, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateBetween(Date value1, Date value2) {
			addCriterion("lastLoginDate between", value1, value2, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andLastlogindateNotBetween(Date value1, Date value2) {
			addCriterion("lastLoginDate not between", value1, value2, "lastlogindate");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNull() {
			addCriterion("openID is null");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNotNull() {
			addCriterion("openID is not null");
			return (Criteria) this;
		}

		public Criteria andOpenidEqualTo(String value) {
			addCriterion("openID =", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotEqualTo(String value) {
			addCriterion("openID <>", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThan(String value) {
			addCriterion("openID >", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThanOrEqualTo(String value) {
			addCriterion("openID >=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThan(String value) {
			addCriterion("openID <", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThanOrEqualTo(String value) {
			addCriterion("openID <=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLike(String value) {
			addCriterion("openID like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotLike(String value) {
			addCriterion("openID not like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidIn(List<String> values) {
			addCriterion("openID in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotIn(List<String> values) {
			addCriterion("openID not in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidBetween(String value1, String value2) {
			addCriterion("openID between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotBetween(String value1, String value2) {
			addCriterion("openID not between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andLogintimesIsNull() {
			addCriterion("loginTimes is null");
			return (Criteria) this;
		}

		public Criteria andLogintimesIsNotNull() {
			addCriterion("loginTimes is not null");
			return (Criteria) this;
		}

		public Criteria andLogintimesEqualTo(Integer value) {
			addCriterion("loginTimes =", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotEqualTo(Integer value) {
			addCriterion("loginTimes <>", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesGreaterThan(Integer value) {
			addCriterion("loginTimes >", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("loginTimes >=", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesLessThan(Integer value) {
			addCriterion("loginTimes <", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesLessThanOrEqualTo(Integer value) {
			addCriterion("loginTimes <=", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesIn(List<Integer> values) {
			addCriterion("loginTimes in", values, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotIn(List<Integer> values) {
			addCriterion("loginTimes not in", values, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesBetween(Integer value1, Integer value2) {
			addCriterion("loginTimes between", value1, value2, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotBetween(Integer value1, Integer value2) {
			addCriterion("loginTimes not between", value1, value2, "logintimes");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScorecountIsNull() {
			addCriterion("scoreCount is null");
			return (Criteria) this;
		}

		public Criteria andScorecountIsNotNull() {
			addCriterion("scoreCount is not null");
			return (Criteria) this;
		}

		public Criteria andScorecountEqualTo(Integer value) {
			addCriterion("scoreCount =", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountNotEqualTo(Integer value) {
			addCriterion("scoreCount <>", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountGreaterThan(Integer value) {
			addCriterion("scoreCount >", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountGreaterThanOrEqualTo(Integer value) {
			addCriterion("scoreCount >=", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountLessThan(Integer value) {
			addCriterion("scoreCount <", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountLessThanOrEqualTo(Integer value) {
			addCriterion("scoreCount <=", value, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountIn(List<Integer> values) {
			addCriterion("scoreCount in", values, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountNotIn(List<Integer> values) {
			addCriterion("scoreCount not in", values, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountBetween(Integer value1, Integer value2) {
			addCriterion("scoreCount between", value1, value2, "scorecount");
			return (Criteria) this;
		}

		public Criteria andScorecountNotBetween(Integer value1, Integer value2) {
			addCriterion("scoreCount not between", value1, value2, "scorecount");
			return (Criteria) this;
		}

		public Criteria andMuteIsNull() {
			addCriterion("mute is null");
			return (Criteria) this;
		}

		public Criteria andMuteIsNotNull() {
			addCriterion("mute is not null");
			return (Criteria) this;
		}

		public Criteria andMuteEqualTo(Integer value) {
			addCriterion("mute =", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteNotEqualTo(Integer value) {
			addCriterion("mute <>", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteGreaterThan(Integer value) {
			addCriterion("mute >", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteGreaterThanOrEqualTo(Integer value) {
			addCriterion("mute >=", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteLessThan(Integer value) {
			addCriterion("mute <", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteLessThanOrEqualTo(Integer value) {
			addCriterion("mute <=", value, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteIn(List<Integer> values) {
			addCriterion("mute in", values, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteNotIn(List<Integer> values) {
			addCriterion("mute not in", values, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteBetween(Integer value1, Integer value2) {
			addCriterion("mute between", value1, value2, "mute");
			return (Criteria) this;
		}

		public Criteria andMuteNotBetween(Integer value1, Integer value2) {
			addCriterion("mute not between", value1, value2, "mute");
			return (Criteria) this;
		}

		public Criteria andIsadminIsNull() {
			addCriterion("isAdmin is null");
			return (Criteria) this;
		}

		public Criteria andIsadminIsNotNull() {
			addCriterion("isAdmin is not null");
			return (Criteria) this;
		}

		public Criteria andIsadminEqualTo(Integer value) {
			addCriterion("isAdmin =", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminNotEqualTo(Integer value) {
			addCriterion("isAdmin <>", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminGreaterThan(Integer value) {
			addCriterion("isAdmin >", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminGreaterThanOrEqualTo(Integer value) {
			addCriterion("isAdmin >=", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminLessThan(Integer value) {
			addCriterion("isAdmin <", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminLessThanOrEqualTo(Integer value) {
			addCriterion("isAdmin <=", value, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminIn(List<Integer> values) {
			addCriterion("isAdmin in", values, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminNotIn(List<Integer> values) {
			addCriterion("isAdmin not in", values, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminBetween(Integer value1, Integer value2) {
			addCriterion("isAdmin between", value1, value2, "isadmin");
			return (Criteria) this;
		}

		public Criteria andIsadminNotBetween(Integer value1, Integer value2) {
			addCriterion("isAdmin not between", value1, value2, "isadmin");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Fri Apr 29 12:50:43 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 19 16:12:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}